apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mlapp
  labels:
    name:  mlapp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: mlapp
  template:
    metadata:
      labels:
        name:  mlapp
    spec:
      containers:
      - image:  balanus/mlapp:gunicon
        name:  mlapp
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /time
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /time
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  PORT
          value:  "5000"
        ports:
        - containerPort:  5000
          name:  mlapp-port
        imagePullPolicy: Always
      restartPolicy: Always